version: '3'

services:
  ah-gateway:
    container_name: ah-gateway
    build:
      context: ..
      dockerfile: Raft.Gateway/Dockerfile
    ports:
      - "344:8080"
    environment:
      - nodes=ah-node-1,ah-node-2,ah-node-3

  ah-node-1:
    container_name: ah-node-1
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-2,ah-node-3

  ah-node-2:
    container_name: ah-node-2
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-1,ah-node-3

  ah-node-3:
    container_name: ah-node-3
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-1,ah-node-2

  ah-loki:
    container_name: ah-loki
    image: grafana/loki:latest
    depends_on:
      - ah-gateway
      - ah-node-1
      - ah-node-2
      - ah-node-3

  ah-otel-collector:
    container_name: ah-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - ah-loki

  ah-grafana:
    container_name: ah-grafana
    image: grafana/grafana:latest
    ports:
      - "345:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    depends_on:
      - ah-otel-collector

volumes:
  grafana_data: