version: '3'

services:
  ah-gateway:
    container_name: ah-gateway
    build:
      context: ..
      dockerfile: Raft.Gateway/Dockerfile
    ports:
      - "344:8080"
    environment:
      - nodes=ah-node-1,ah-node-2,ah-node-3

  ah-node-1:
    container_name: ah-node-1
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-2,ah-node-3

  ah-node-2:
    container_name: ah-node-2
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-1,ah-node-3

  ah-node-3:
    container_name: ah-node-3
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    environment:
      - nodes=ah-node-1,ah-node-2