version: '3'

services:
  ah-gateway:
    container_name: ah-gateway
    build:
      context: ..
      dockerfile: Raft.Gateway/Dockerfile
    ports:
      - "344:8080"
    environment:
      - NODES=144.17.92.15:346,144.17.92.15:347,144.17.92.14:348

  ah-node-1:
    container_name: ah-node-1
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    ports:
      - 346:8080 
    environment:
      - NODES=144.17.92.15:347,144.17.92.14:348
      - NODE_ID=144.17.92.15:8080

  ah-node-2:
    container_name: ah-node-2
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    ports:
      - 347:8080
    environment:
      - NODES=144.17.92.15:346,144.17.92.14:348
      - NODE_ID=144.17.92.15:8080

  ah-loki:
    container_name: ah-loki
    image: grafana/loki:latest

  ah-otel-collector:
    container_name: ah-otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - ah-loki

  ah-grafana:
    container_name: ah-grafana
    image: grafana/grafana:latest
    ports:
      - "345:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
    depends_on:
      - ah-otel-collector

volumes:
  grafana_data: