version: '3'

services:
  ah-node-3:
    container_name: ah-node-3
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    ports:
      - 348:8080
    environment:
      - NODES=144.17.92.15:346,144.17.92.15:347
      - NODE_ID=144.17.92.14:348

  ah-shop:
    container_name: ah-shop
    build:
      context: ..
      dockerfile: Raft.Shop/Dockerfile
    ports:
      - 349:8080
