receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  loki:
    endpoint: http://ah-loki:3100/loki/api/v1/push

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]