name: Raftr
run-name: ${{ github.actor }} is deploying 🚀
on: [push]

jobs:
  Build-1:
    runs-on: [self-hosted, raft-1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker images
        run: |
          cd ops
          docker compose -f docker-compose-1.yml build 

  Build-2:
    runs-on: [self-hosted, raft-2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker images
        run: |
          cd ops
          docker compose -f docker-compose-2.yml build 

  Test:
    runs-on: [self-hosted, raft-1]
    needs: [Build-1, Build-2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          dotnet test Raft.Tests 

  Deploy-1:
    runs-on: [self-hosted, raft-1]
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          cd ops
          docker compose up -f docker-compose-1.yml -d 

  Deploy-2:
    runs-on: [self-hosted, raft-2]
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          cd ops
          docker compose up -f docker-compose-2.yml -d 